const el=id=>document.getElementById(id);
let busy=false,pending=[];
const selection=()=>[...document.querySelectorAll('#tables input:checked')].map(x=>x.value);
const status=text=>el('status').textContent=text;
function updateCount(){const boxes=[...document.querySelectorAll('#tables input')],n=selection().length;el('count').textContent=`(${n} selected)`;el('selectAll').checked=boxes.length>0&&n===boxes.length;el('selectAll').indeterminate=n>0&&n<boxes.length;}
function base(){const raw=el('api').value.trim().replace(/\/$/,'');if(!raw)throw Error('Enter the backend API address.');const url=new URL(raw);if(!['http:','https:'].includes(url.protocol))throw Error('Use an HTTP or HTTPS API address.');return raw.replace(/\/api\/rpc$/,'');}
async function request(route,body){const response=await fetch(base()+'/api/database-admin/'+route,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok){const error=await response.json().catch(()=>({message:'Request failed: '+response.status}));throw Error(error.message);}return response;}
async function run(action){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await action();}catch(e){status(e.message);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function load(){status('Loading tables…');const result=await(await request('tables')).json();el('tables').replaceChildren();for(const table of result.tables){const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=table.name;box.onchange=updateCount;label.append(box,document.createTextNode(' '+table.name));el('tables').append(label);}updateCount();status('Tables loaded.');}
async function download(mode){const tables=selection();if(mode==='data'&&!tables.length)throw Error('Select at least one table.');status('Preparing SQL download…');const response=await request('export',{mode,tables});const blob=await response.blob();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(response.headers.get('content-disposition')||'').match(/filename="([^"]+)"/)?.[1]||`textile-${mode}-${new Date().toISOString().replace(/[:.]/g,'-')}.sql`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status('SQL download prepared. Check your browser downloads.');}
el('load').onclick=()=>run(load);
for(const mode of ['full','structure','data'])el(mode).onclick=()=>run(()=>download(mode));
el('selectAll').onchange=()=>{document.querySelectorAll('#tables input').forEach(x=>x.checked=el('selectAll').checked);updateCount();};
el('clear').onclick=()=>{pending=selection();if(!pending.length)return status('Select at least one table.');el('confirmTables').replaceChildren(...pending.map(name=>{const li=document.createElement('li');li.textContent=name;return li;}));el('confirm').showModal();};
el('cancel').onclick=()=>el('confirm').close();
el('confirmClear').onclick=()=>{el('confirm').close();const tables=[...pending];run(async()=>{status('Clearing selected data…');const result=await(await request('clear',{tables,confirmation:'CLEAR SELECTED DATA'})).json();status('Data cleared successfully.\n'+Object.entries(result.deleted).map(([name,count])=>name+': '+count+' rows deleted').join('\n'));});};
const config=window.TEXTILE_CONFIG||{};el('api').value=config.API_BASE_URL||config.apiBaseUrl||config.API_URL||(location.protocol.startsWith('http')?location.origin:'');
